// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"01-practice/internal/dao/internal"
)

// internalCfDetailDao is internal type for wrapping internal DAO implements.
type internalCfDetailDao = *internal.CfDetailDao

// cfDetailDao is the data access object for table cf_detail.
// You can define custom methods on it to extend its functionality as you wish.
type cfDetailDao struct {
	internalCfDetailDao
}

var (
	// CfDetail is globally public accessible object for table cf_detail operations.
	CfDetail = cfDetailDao{
		internal.NewCfDetailDao(),
	}
)

// Fill with you ideas below.
