// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"01-practice/internal/dao/internal"
)

// internalContraryDetailDao is internal type for wrapping internal DAO implements.
type internalContraryDetailDao = *internal.ContraryDetailDao

// contraryDetailDao is the data access object for table contrary_detail.
// You can define custom methods on it to extend its functionality as you wish.
type contraryDetailDao struct {
	internalContraryDetailDao
}

var (
	// ContraryDetail is globally public accessible object for table contrary_detail operations.
	ContraryDetail = contraryDetailDao{
		internal.NewContraryDetailDao(),
	}
)

// Fill with you ideas below.
