// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"01-practice/internal/dao/internal"
)

// internalGoodsListDetailDao is internal type for wrapping internal DAO implements.
type internalGoodsListDetailDao = *internal.GoodsListDetailDao

// goodsListDetailDao is the data access object for table goods_list_detail.
// You can define custom methods on it to extend its functionality as you wish.
type goodsListDetailDao struct {
	internalGoodsListDetailDao
}

var (
	// GoodsListDetail is globally public accessible object for table goods_list_detail operations.
	GoodsListDetail = goodsListDetailDao{
		internal.NewGoodsListDetailDao(),
	}
)

// Fill with you ideas below.
