// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"01-practice/internal/dao/internal"
)

// internalGoodsListDao is internal type for wrapping internal DAO implements.
type internalGoodsListDao = *internal.GoodsListDao

// goodsListDao is the data access object for table goods_list.
// You can define custom methods on it to extend its functionality as you wish.
type goodsListDao struct {
	internalGoodsListDao
}

var (
	// GoodsList is globally public accessible object for table goods_list operations.
	GoodsList = goodsListDao{
		internal.NewGoodsListDao(),
	}
)

// Fill with you ideas below.
