// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"01-practice/internal/dao/internal"
)

// internalKingHonourDetailDao is internal type for wrapping internal DAO implements.
type internalKingHonourDetailDao = *internal.KingHonourDetailDao

// kingHonourDetailDao is the data access object for table king_honour_detail.
// You can define custom methods on it to extend its functionality as you wish.
type kingHonourDetailDao struct {
	internalKingHonourDetailDao
}

var (
	// KingHonourDetail is globally public accessible object for table king_honour_detail operations.
	KingHonourDetail = kingHonourDetailDao{
		internal.NewKingHonourDetailDao(),
	}
)

// Fill with you ideas below.
