// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"01-practice/internal/dao/internal"
)

// internalKingGunplayDetailDao is internal type for wrapping internal DAO implements.
type internalKingGunplayDetailDao = *internal.KingGunplayDetailDao

// kingGunplayDetailDao is the data access object for table king_gunplay_detail.
// You can define custom methods on it to extend its functionality as you wish.
type kingGunplayDetailDao struct {
	internalKingGunplayDetailDao
}

var (
	// KingGunplayDetail is globally public accessible object for table king_gunplay_detail operations.
	KingGunplayDetail = kingGunplayDetailDao{
		internal.NewKingGunplayDetailDao(),
	}
)

// Fill with you ideas below.
