// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"01-practice/internal/dao/internal"
)

// internalMissionSummonDetailDao is internal type for wrapping internal DAO implements.
type internalMissionSummonDetailDao = *internal.MissionSummonDetailDao

// missionSummonDetailDao is the data access object for table mission_summon_detail.
// You can define custom methods on it to extend its functionality as you wish.
type missionSummonDetailDao struct {
	internalMissionSummonDetailDao
}

var (
	// MissionSummonDetail is globally public accessible object for table mission_summon_detail operations.
	MissionSummonDetail = missionSummonDetailDao{
		internal.NewMissionSummonDetailDao(),
	}
)

// Fill with you ideas below.
