// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"01-practice/internal/dao/internal"
)

// internalNinjaDetailDao is internal type for wrapping internal DAO implements.
type internalNinjaDetailDao = *internal.NinjaDetailDao

// ninjaDetailDao is the data access object for table ninja_detail.
// You can define custom methods on it to extend its functionality as you wish.
type ninjaDetailDao struct {
	internalNinjaDetailDao
}

var (
	// NinjaDetail is globally public accessible object for table ninja_detail operations.
	NinjaDetail = ninjaDetailDao{
		internal.NewNinjaDetailDao(),
	}
)

// Fill with you ideas below.
