// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"01-practice/internal/dao/internal"
)

// internalQqCardDetailDao is internal type for wrapping internal DAO implements.
type internalQqCardDetailDao = *internal.QqCardDetailDao

// qqCardDetailDao is the data access object for table qq_card_detail.
// You can define custom methods on it to extend its functionality as you wish.
type qqCardDetailDao struct {
	internalQqCardDetailDao
}

var (
	// QqCardDetail is globally public accessible object for table qq_card_detail operations.
	QqCardDetail = qqCardDetailDao{
		internal.NewQqCardDetailDao(),
	}
)

// Fill with you ideas below.
