// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"01-practice/internal/dao/internal"
)

// internalSkuSceneDao is internal type for wrapping internal DAO implements.
type internalSkuSceneDao = *internal.SkuSceneDao

// skuSceneDao is the data access object for table sku_scene.
// You can define custom methods on it to extend its functionality as you wish.
type skuSceneDao struct {
	internalSkuSceneDao
}

var (
	// SkuScene is globally public accessible object for table sku_scene operations.
	SkuScene = skuSceneDao{
		internal.NewSkuSceneDao(),
	}
)

// Fill with you ideas below.
